### ISSUE TITLE
Issue when integrating with React application

### ISSUE THREAD

**Issue by satyam90** [urakozz/tesseract.ts#5]
I'm building React Web application using type script and integrating "Tesseract".
I'm using Mac and when compiling, I'm seeing below error:

_Failed to compile.

./node_modules/tesseract.ts/dist/index.js
Module not found: Can't resolve 'tesseract.js/dist/tesseract' in '/Users/satya/temp/raysecure/node_modules/tesseract.ts/dist'_

In my package.json, entries are:

"tesseract.js": "^2.1.1",
"tesseract.ts": "^1.1.2"

Can you suggest me what could be possible reason for this?
Or is there a fix that has to be implemented?

**Comment by urakozz** [comment]
My idiotic library works only for the first version (only for the browser), I guess they fixed import issue in the v2, so you don't need my hack anymore

**Comment by satyam90** [comment]
Its a good library.... you did a good job by creating a repository. You should have just maintained it.

**Comment by urakozz** [comment]
@satyam90 This is open source, if you want to improve something - feel free to contribute and send a PR. I do not **have** to maintain it.
